name: Python CI

on:
  push:
    branches:
      - main  # Указываем, что workflow будет срабатывать на ветке main

jobs:
  build:

    runs-on: ubuntu-20.04  # Используем фиксированную версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Укажите необходимую версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Если файл requirements.txt отсутствует, можно закомментировать следующую строку
        # pip install -r requirements.txt  
    
    - name: Run tests
      run: |
        python -m unittest main/circle_test.py
